### ISSUE TITLE
Corrupted GoogleColab!

### ISSUE THREAD

**Issue by afshinebtia** [Dieblitzen/cs224w-project#1]
Hello,
Would you please modify the GoogleColab link? It's already corrupted.

Thanks!

**Comment by afshinebtia** [comment]
> 

Also, can you add a step-by-step description to run the code and see the result?
It's not even really clear on the MEdium website.

**Comment by samar-khanna** [comment]
Thanks for pointing this out! Closing the issue since we have updated the Colab link.
